export const timetable_example = [
  [
    {},
    {
      subject: 'כימיה',
      teacher: 'זרסקי יפעת',
      class: 'כימיה מעבדה 2',
      modification: 1,
      modData: 'קוסטיה',
    },
    {
      subject: 'כימיה',
      teacher: 'זרסקי יפעת',
      class: 'כימיה מעבדה 2',
      modification: 5,
      modData: 'חח כימיה זה מקצוע הומני חח',
    },
    {
      subject: 'היסטוריה',
      teacher: 'אשכנזי חיים',
      class: 'חדר י 7',
    },
    {
      subject: 'הבעה ולשון',
      teacher: 'אהרון שוחט גלית',
      class: 'חדר י 7',
      modification: 3,
      modData: 'שכנר איתי',
    },
    {
      subject: 'מתמטיקה 5',
      teacher: 'טיראן חוה',
      class: 'חדר י 6',
      modification: 2,
      modData: 'מבחן? אה שכחתי אתה לא לומד מתמטיקה',
    },
    {
      subject: 'מתמטיקה 5',
      teacher: 'טיראן חוה',
      class: 'חדר י 6',
    },
    {
      subject: 'חנג בנים',
      teacher: 'פריזה אמיר',
      class: '',
    },
    {},
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {
      subject: 'היסטוריה',
      teacher: 'אשכנזי חיים',
      class: 'חדר י 7',
    },
    {
      subject: 'היסטוריה',
      teacher: 'אשכנזי חיים',
      class: 'חדר י 7',
    },
    {
      subject: 'השכלה כללית א',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 7',
    },
    {
      subject: 'אנגלית 5',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 3',
    },
    {
      subject: 'אנגלית 5',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 3',
    },
    {
      subject: 'כימיה',
      teacher: 'זרסקי יפעת',
      class: 'כימיה מעבדה 2',
    },
    {},
    {},
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {
      subject: 'מתמטיקה 5',
      teacher: 'טיראן חוה',
      class: 'חדר י 6',
    },
    {
      subject: 'מתמטיקה 5',
      teacher: 'טיראן חוה',
      class: 'חדר י 6',
    },
    {
      subject: 'תנ"ך',
      teacher: 'ארבל אסף',
      class: 'חדר י 7',
    },
    {
      subject: 'חינוך',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 7',
    },
    {
      subject: 'מדעי המחשב יחל 1',
      teacher: 'זבלינסקי קונסטנטין',
      class: 'חדר מחשב שכבה  ז',
    },
    {
      subject: 'מדעי המחשב יחל 1',
      teacher: 'זבלינסקי קונסטנטין',
      class: 'חדר מחשב שכבה  ז',
    },
    {
      subject: 'הבעה ולשון',
      teacher: 'אהרון שוחט גלית',
      class: 'חדר י 7',
    },
    {},
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {
      subject: 'מתמטיקה 5',
      teacher: 'וינשטוק ענת',
      class: 'מקוון סינכרוני',
    },
    {
      subject: 'השכלה כללית',
      teacher: 'בן אליעזר אודי',
      class: 'מקוון סינכרוני',
    },
    {},
    {
      subject: 'מדעי המחשב יחל 1',
      teacher: 'זבלינסקי קונסטנטין',
      class: 'חדר מחשב שכבה  ז',
    },
    {
      subject: 'השכלה כללית',
      teacher: 'בן אליעזר אודי',
      class: 'חדר י 7',
    },
    {
      subject: 'אנגלית 5',
      teacher: 'ורגוליס ארתור',
      class: 'מקוון אסינכרוני',
    },
    {},
    {
      subject: 'כימיה',
      teacher: 'זרסקי יפעת',
      class: 'מקוון סינכרוני',
    },
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {
      subject: 'תנ"ך',
      teacher: 'ארבל אסף',
      class: 'חדר י 7',
    },
    {
      subject: 'תנ"ך',
      teacher: 'ארבל אסף',
      class: 'חדר י 7',
    },
    {
      subject: 'אנגלית 5',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 3',
    },
    {
      subject: 'אנגלית 5',
      teacher: 'ורגוליס ארתור',
      class: 'חדר י 3',
    },
    {
      subject: 'הבעה ולשון',
      teacher: 'אהרון שוחט גלית',
      class: 'חדר י 7',
    },
    {
      subject: 'חנג בנים',
      teacher: 'פריזה אמיר',
      class: '',
    },
    {},
    {},
    {},
    {},
    {},
    {},
  ],
  [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
  [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
]

export const options_example = [
  {
    subject: 'אנגלית',
    teacher: 'סבג טסי',
    class: 'חדר ז 2',
  },
  {
    subject: 'אנגלית',
    teacher: 'סער אסנת',
    class: 'חדר י 7',
  },
  {
    subject: 'אנגלית האצה',
    teacher: 'רייס יעל',
    class: 'חדר ז 1',
  },
  {
    subject: 'אנגלית',
    teacher: 'קישנר לאה',
    class: 'חדר ז 4',
  },
  {
    subject: 'אנגלית',
    teacher: 'שוורץ יעל',
    class: 'חדר ז 6 אקוסטי',
  },
  {
    subject: 'אנגלית',
    teacher: 'גורן ענבל',
    class: 'חדר ז 5 אקוסטי',
  },
]
